replicaCount: 1

serviceAccount:
  create: true  # Or false, depending on whether you want to create the service account


# Container image configuration
image:
  repository: docker.io/anilkumarprime/tomcatui
  pullPolicy: IfNotPresent
  tag: "v4"

# Service configuration
service:
  type: LoadBalancer   # Exposes the service externally
  port: 80             # The port on which the service is exposed
  targetPort: 8080     # The port on the container to which the traffic is forwarded

# Resource limits and requests (optional, good practice)
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
