replicaCount: 1

# Container image configuration
image:
  repository: docker.io/anilkumarprime/tomcatui
  pullPolicy: IfNotPresent
  tag: "v4"

# Service configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# Resource limits and requests
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

# Service Account configuration
serviceAccount:
  create: true  # Change to false if you don't want to create a service account
  name: ""      # Optional, if you want to specify an existing service account

# Enable or disable ingress
ingress:
  enabled: false

# Enable or disable autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Optional node selectors, tolerations, and affinity
nodeSelector: {}
tolerations: []
affinity: {}
