replicaCount: 1

# Container image configuration
image:
  repository: docker.io/anilkumarprime/tomcatui
  pullPolicy: IfNotPresent
  tag: "v4"

# Service configuration
service:
  type: NodePort
  port: 80
  targetPort: 8080

# Resource limits and requests
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
