apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tomcat.fullname" . }}
  labels:
    {{- include "tomcat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tomcat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tomcat.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8068  # Set container port to 8080 (Tomcat default)
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
